### ISSUE TITLE
Serialization errors when attempting to perform operations on null-containing geometries

### ISSUE THREAD

**Issue by sonjoonho** [duckdb/duckdb_spatial#292] opened 2024-03-25 18:57 UTC
I'm trying to perform a query similar to below which essentially finds the shortest distance from each point in `table_with_points` (O(thousands of rows)) containing latitudes and longitudes to any polygon in `table_with_polygons` (O(tens of thousands of rows)) which contains WKT representations of multi-polygons.

```sql
SELECT
      distance
    FROM table_with_points
    LEFT JOIN (
      SELECT
        ST_Distance (
            ST_GeomFromText(shape),
            ST_Point (lat, long)
        ) AS distance
      FROM
        table_with_polygons
      ORDER BY distance
        limit 1
    ) ON true
 ```

When I run this query I seem to either get 

```
Error: Not implemented Error: GEOS Deserialize: Geometry type <large number e.g. 49, 87, 215> not supported
```

or 

```
Error: Serialization Error: Trying to read past end of buffer
```

**Comment by Maxxen** [comment] 2024-03-25 20:19
Hi! Thanks for reporting this issue! Spatial is currently suffering from a lot of regressions, but I will try to have a look soon. Could you provide some data for a minimum reproducible example or could you tell me anything about the nature of your polygons (do they contain z/m values, lots of holes, etc?)

**Comment by Maxxen** [comment] 2024-04-22 10:32
The last trace of the error message is from an older spatial version (DuckDB v0.9.1) and I can't reproduce it now (NULL's are properly propagated) so Im going to go ahead and close this.

**Closed by Maxxen** 2024-04-22 10:32 UTC
